{% set version = load_setup_py_data().get('version') %}

package:
    name: asvdb
    version: {{ version }}

source:
    path: ..

build:
    string: {{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    script: {{ PYTHON }} -m pip install . --no-deps
    noarch: python

requirements:
    host:
        - python

    run:
        - python
        - boto3
        - botocore
test:
    imports:
        - asvdb

about:
    home: https://github.com/rapidsai/asvdb
    license: Apache 2.0
